### PR TITLE
fix(tur/code-server): mark as unsafe for on-device builds

### LINKED ISSUE #1598: [Bug]: code-server is not safe for on-device builds
### Problem description

`code-server` `build.sh` runs this which causes any type of Termux to crash and become almost unrecoverable

https://github.com/termux-user-repository/tur/blob/07e143f56c1572b6de3537eabbf86387e2fcdae0/tur/code-server/build.sh#L50

### What steps will reproduce the bug?

> [!CAUTION]
> `code-server` is not safe for on-device builds. **Do not run** these commands in any `$TERMUX_ON_DEVICE_BUILD=true` environment unless a PR has closed this issue.

```
git clone https://github.com/termux-user-repository/tur.git
cd tur/
./setup-environment.sh
scripts/setup-termux.sh
./build-package.sh -I -f code-server
```

### What is the expected behavior?

Maybe there could be a way to correctly build the software on-device in the future, but for now, it is a high priority to show this in order to make sure that the termux installation does not become corrupted:

```
ERROR: Package 'code-server' is not safe for on-device builds.
```

### System information

technically, it could be pointed out that I should not be able to show this because, unfortunately, my termux installation became corrupted.

Thankfully, Termux has a safe mode, ["failsafe session"](https://wiki.termux.com/wiki/Recover_a_broken_environment), that can be used to recover from this using this command:

```
mv /data/data/com.termux/files/usr/bin.bp /data/data/com.termux/files/usr/bin
```

On the other hand, in my case, my device was a termux-docker. Therefore, at first glance, it might appear that termux-docker does not have the failsafe session and cannot be recovered.

However, it is very fortunate that I happen to know that termux-docker **does** have the failsafe session and it **can** be used to almost fully recover from this bug.

I will post the full commands to recover from this using the failsafe session within termux-docker.

```bash
docker container ls -a # note container ID of the corrupted container
docker commit e2013248a61b termux-docker-corrupted-backup
docker run -it --entrypoint=/system/bin/sh termux/termux-docker-corrupted-backup
/system/bin/mv /data/data/com.termux/files/usr/bin.bp /data/data/com.termux/files/usr/bin
exit
docker container ls -a # note container ID of the failsafe container
docker commit e0121678d912 termux-docker-recovered-backup
docker run -it --entrypoint=/entrypoint.sh termux-docker-recovered-backup
exit
# if desired, remove the corrupted container, the recovery container and the transitional backup
docker container rm e0121678d912 e2013248a61b
docker image rm termux-docker-corrupted-backup
```

After doing that, now I am able to get `termux-info` from the recovered termux-docker container.

```
/data/data/com.termux/files/usr/bin/getprop: 3: exec: /system/bin/getprop: not found
/data/data/com.termux/files/usr/bin/getprop: 3: exec: /system/bin/getprop: not found
/data/data/com.termux/files/usr/bin/getprop: 3: exec: /system/bin/getprop: not found
/data/data/com.termux/files/usr/bin/getprop: 3: exec: /system/bin/getprop: not found
Termux Variables:
unsupported
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://mirror.mwt.me/termux/main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.44.6
Android version:

Kernel build information:
Linux 513cc98a85e6 6.9.0-1-aarch64-ARCH #2 SMP PREEMPT_DYNAMIC Wed Jun 26 15:54:36 CDT 2024 armv8l Android
Device manufacturer:

Device model:

LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

### PR DESCRIPTION
**Pull request by robertkirkman**
- Fixes #1598

### CODE REVIEW

**Comment by licy183** [comment]
I really don't want to check every package for the safety for on-device build. It is better to set `TERMUX_PKG_ON_DEVICE_BUILD_NOT_SUPPORTED=true` in `build.sh`.

File: tur/code-server/build.sh [hunk 1]
```diff
@@ -3,13 +3,15 @@ TERMUX_PKG_DESCRIPTION="Run VS Code on any machine anywhere and access it in the
 TERMUX_PKG_LICENSE="MIT"
 TERMUX_PKG_MAINTAINER="@termux-user-repository"
 TERMUX_PKG_VERSION="4.98.2"
+TERMUX_PKG_REVISION=1
```
Comment (licy183) [inline tur/code-server/build.sh]:
```suggestion
```

And add `[skip ci]` in the commit message. There is no need to revbump this.

Comment (robertkirkman) [reply tur/code-server/build.sh]: Ok I have done that
